title: Datoptron
email: datoptron@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Datoptron is a spinoff company of the National Technical University of Athens
  in the area of Artificial Intelligence. We leverage 20 years experience in
  Semantic Technologies, Machine Learning and Crowdsourcing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://datoptron.github.io/datoptron-website" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Add a directory to hold the pages
include: ["_pages"]

# Wire in the SASS files
sass:
  sass_dir: assets/_sass
  style: compressed

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
